version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-todo-api
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_api
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todo-network

  app:
    build: .
    container_name: springboot_app
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/todo_api
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - todo-network

volumes:
  mysql_data:

networks:
  todo-network:
    driver: bridge
